# Generated by Django 5.1.1 on 2024-09-16 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine_Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Review_Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('description', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('capacity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('status_available', models.IntegerField()),
                ('status_health', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('machine_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry.machine_size')),
            ],
        ),
        migrations.CreateModel(
            name='Reserve_Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('cost', models.IntegerField()),
                ('arrive_at', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'waiting'), (1, 'workable'), (2, 'working'), (3, 'complete'), (4, 'retrivable')])),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('arrive_arrive', models.DateTimeField(null=True)),
                ('work_at', models.DateTimeField(null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry.machine')),
                ('machine_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry.machine_size')),
                ('service', models.ManyToManyField(related_name='reserve_service', to='laundry.service')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.TextField()),
                ('role', models.CharField(choices=[('cus', 'customer'), ('stf', 'staff'), ('mgr', 'manager')])),
                ('status', models.BooleanField(default=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('reserveMachine', models.ManyToManyField(through='laundry.Reserve_Machine', to='laundry.machine')),
            ],
        ),
        migrations.AddField(
            model_name='reserve_machine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry.user'),
        ),
    ]
