# Generated by Django 5.1.1 on 2024-09-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='status_health',
            field=models.IntegerField(default=0),
        ),
    ]
