# Generated by Django 5.1.1 on 2024-09-27 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve_machine',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laundry_model.machine'),
        ),
    ]
