# Generated by Django 5.1.1 on 2024-09-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='status_available',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='machine',
            name='status_health',
            field=models.BooleanField(default=1),
        ),
    ]
