# Generated by Django 5.1.1 on 2024-09-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_model', '0002_alter_machine_status_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='status_health',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reserve_machine',
            name='status',
            field=models.IntegerField(choices=[(0, 'waiting'), (1, 'workable'), (2, 'working'), (3, 'complete'), (4, 'retrivable')], default=0),
        ),
        migrations.AlterField(
            model_name='review_reserve',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
