# Generated by Django 5.1.1 on 2024-09-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_model', '0002_alter_reserve_machine_machine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve_machine',
            old_name='arrive_arrive',
            new_name='actual_arrive',
        ),
    ]
